# Generated by Django 5.2 on 2025-04-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Колір',
                'verbose_name_plural': 'Кольори',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип взуття',
                'verbose_name_plural': 'Типи взуття',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва взуття')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото товару')),
                ('size', models.CharField(max_length=10, verbose_name='Розмір')),
                ('season', models.CharField(choices=[('весна-літо', 'весна-літо'), ('осінь-зима', 'осінь-зима')], max_length=10, verbose_name='Сезон')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Бестселер')),
                ('is_new_shoes', models.BooleanField(default=False, verbose_name='Нові надходження')),
                ('is_active', models.BooleanField(default=True, verbose_name='Товар на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення товару')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення товару')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.colors', verbose_name='Колір')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.materials', verbose_name='Матеріал')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.types', verbose_name='Тип взуття')),
            ],
            options={
                'verbose_name': 'Взуття',
                'verbose_name_plural': 'Взуття',
            },
        ),
    ]
