# Generated by Django 5.2 on 2025-04-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Список взуття', 'verbose_name_plural': 'Список взуття'},
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(max_length=10, null=True, verbose_name='Розмір'),
        ),
    ]
