# Generated by Django 5.2 on 2025-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoes_options_alter_shoes_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='size',
        ),
        migrations.AddField(
            model_name='shoes',
            name='size_from',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Розмір з'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size_to',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Розмір по'),
        ),
    ]
