# Generated by Django 5.2 on 2025-04-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_remove_shoes_size_shoes_size_from_shoes_size_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to='images/main_image', verbose_name='Головне фото товару'),
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/shoes/', verbose_name='Фото товару')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes.shoes', verbose_name='Товар')),
            ],
        ),
    ]
