# Generated by Django 5.2 on 2025-05-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_shoes_image_shoeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.colors', verbose_name='колір'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення товару'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to='images/main_image', verbose_name='головне фото товару'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='товар на сайті'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='бестселер'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='is_new_shoes',
            field=models.BooleanField(default=False, verbose_name='нові надходження'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.materials', verbose_name='матеріал'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='назва взуття'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='ціна'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='season',
            field=models.CharField(choices=[('весна-літо', 'весна-літо'), ('осінь-зима', 'осінь-зима')], max_length=10, verbose_name='сезон'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size_from',
            field=models.IntegerField(default=36, max_length=10, null=True, verbose_name='розмір з'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size_to',
            field=models.IntegerField(default=41, max_length=10, null=True, verbose_name='розмір по'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.types', verbose_name='тип взуття'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата оновлення товару'),
        ),
    ]
