# Generated by Django 5.2 on 2025-05-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_shoes_color_alter_shoes_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
